language: java

jdk:
    - oraclejdk8

notifications:
    webhooks:
        urls:
            - secure: "vS/3iuMRuwLYMjd8U6z3CUDGbQhjRC0+szQzUDNkeVBz01hzJnQ+OEXLuGoNfS0rKaBIoPW7pmN6Rp3Sn2W2JexrpqvpiUnet5eodZMpiwqOkNjuJPG4qywGed1tnZlpqtAPLgQ9cUvRfkAsVsDwUc+ZtYR7E2IIfDiUMJqLPZo="
        on_success: always
        on_failure: always
        on_start: false