language: groovy

jdk:
    - oraclejdk8

# Use container build
sudo: false

cache:
    directories:
    - $HOME/.gradle

# Shell nop (install handled by gradle dependency management, no need to first assemble and then test)
install: ":"

before_script:
    # Gradle daemon won't add any benefit since Travis builds are always from scratch
    - export GRADLE_OPTS='-Dorg.gradle.daemon=false'
    - chmod +x gradlew

script: "./gradlew distAndTest --info"

deploy:
  provider: releases
  api-key:
    secure: "CJyVgIoL/G0a233WuqPi14eOAk8JlWdErxqbJZYawGmCt5CBJW9l5+4CO4mJqho+EKHmpr+OgGVFq5HV4zQVqVJNFhL86yEucY52v3uQqqT26UmyJwLEtNOpHzVw0pXKvE5LbBOQdl+/8nNhakd6VwGE3qs05F+0ZYyu9LXaal4="
  file_glob: true
  file: "build/distributions/cardshifter-*.zip"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    #must remain on all_branches: true together with tags: true due to the following bug: https://github.com/travis-ci/travis-ci/issues/1675
    #ideal situation would be to change it such that it only builds a release on the master branch on tag push